workflows:
  build-android:
    name: Build APK for Android
    max_build_duration: 20
    environment:
      flutter: "3.22.0"
      android_signing:
        use_keystore: false
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
